spring: 
 profiles: 
 active: 
   - dev

---
spring: 
 profiles: dev
  application: 
   name: microservicecloud-config-pz-devxxx
---
spring: 
 profiles: test
  application: 
   name: microservicecloud-config-pz-dev