srping: 
 profiles: 
  active: 
   - dev

---
srping: 
 profiles: dev
  application: 
   name: microservicecloud-config-pz-devxxx
---
srping: 
 profiles: test
  application: 
   name: microservicecloud-config-pz-dev